FROM node:20-alpine

WORKDIR /app

# Копируем package.json и устанавливаем зависимости
COPY package*.json ./
RUN npm ci

EXPOSE 5173

# Команда будет переопределена в docker-compose
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
