version: "3.8"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - parser
    networks:
      - app-network

  parser:
    build:
      context: ./parser
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - AI_SERVICE_URL=${AI_SERVICE_URL}
      - AI_SERVICE_API_KEY=${AI_SERVICE_API_KEY}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
